### ISSUE TITLE
Can this be ran inside the browser? 

### ISSUE THREAD

**Issue by adamSplendex** [elemaudio/effects-plugin#14]
Hello!

Pretty neat stuff here, i wonder if anyone could use this plugin inside the browser? 

There are some usecases I am looking for:

- realtime reverb settings inside the browser - even lowlatency webworker / audioworklet solution
- bounce audio from browser with reverb

I searched but i did not see any answer nor in elementary audio docs nor here.

Thanks in advance <3

**Comment by nick-thompson** [comment]
Hey @adamSplendex sorry for the delay.

The short answer is yes! It's not a copy/paste, but it's quite close. The UI is all web technology in the first place, and the audio graph is primarily built (or at least, described) with JavaScript. The primary difference is that to run SRVB in the browser you would need to take that audio graph description and send it to a [WebRenderer](https://www.elementary.audio/docs/packages/web-renderer) instance instead of sending it over to the C++ engine that SRVB uses. As an example, check out this Elements project which is an in-browser synthesizer and uses this SRVB algorithm for its reverb: https://github.com/chromatone/elements/blob/main/elements/fx/srvb.js.

Closing here hoping that's a helpful answer, but please feel free to reopen if you have more questions!
